networks:
  default:
    name: test-network
    driver: bridge

services:
    redis-db:
        image: redislabs/redismod:latest
        command: ['--loadmodule', '/usr/lib/redis/modules/rejson.so', '--loadmodule', '/usr/lib/redis/modules/redisearch.so', '--appendonly', 'yes']
        restart: always

    app:
        build:
            context: ./app
            dockerfile: app.dockerfile
        environment:
            REDIS_OM_URL: redis://redis-db:6379
        volumes:
            - ./app:/app
            - ./setups:/setups
        tty: true

    redisinsight:
        image: redislabs/redisinsight:latest
        ports:
            - 8001:8001
        restart: always